import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import "./globals.css";
import Header from "../components/Header";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={fontSans.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
